# Generated by Django 3.2.7 on 2021-09-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='images',
            field=models.TextField(blank=True, null=True),
        ),
    ]
