# Generated by Django 3.2.7 on 2021-09-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mag', '0002_alter_article_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
